#pragma once

// [B] THE ONE BRIDGE to the vendored bt3gl (raylib) tree. GENERATED by
// tools/vendor/rename_to_bt3api.ps1 -- do not hand-edit: re-run the script.
//
// Our code speaks bt3*/BT3_* API; the vendor keeps upstream names byte-for-byte in
// third_party/bt3gl so it stays trivially updatable. Include THIS, not "raylib.h"/"rlgl.h".

#include "raylib.h"
#include "rlgl.h"

// ---- types -------------------------------------------------------------------------
using bt3Vector2 = Vector2;
using bt3Rectangle = Rectangle;
using bt3Image = Image;
using bt3Texture2D = Texture2D;
using bt3RenderTexture2D = RenderTexture2D;
using bt3Music = Music;
using bt3Sound = Sound;          // [netsfx] UI sound effects for the Dragon Net menu
using bt3AudioStream = AudioStream;
using bt3Color = Color;          // [netmenu2d] the custom Dragon Net menu
using bt3Font = Font;            // [netmenu2d]

// ---- functions ---------------------------------------------------------------------
#define bt3BeginBlendMode BeginBlendMode
#define bt3BeginDrawing BeginDrawing
#define bt3BeginShaderMode BeginShaderMode
#define bt3BeginTextureMode BeginTextureMode
#define bt3ClearBackground ClearBackground
#define bt3CloseWindow CloseWindow
#define bt3DrawRectangle DrawRectangle
#define bt3DrawTexturePro DrawTexturePro
#define bt3DrawTriangle DrawTriangle
#define bt3EndBlendMode EndBlendMode
#define bt3EndDrawing EndDrawing
#define bt3EndShaderMode EndShaderMode
#define bt3EndTextureMode EndTextureMode
#define bt3ExportImage ExportImage
#define bt3GenImageColor GenImageColor
#define bt3GenTextureMipmaps GenTextureMipmaps
#define bt3GetCharPressed GetCharPressed
#define bt3GetCurrentMonitor GetCurrentMonitor
#define bt3GetGamepadAxisCount GetGamepadAxisCount
#define bt3GetGamepadAxisMovement GetGamepadAxisMovement
#define bt3GetImageColor GetImageColor
#define bt3GetKeyPressed GetKeyPressed
#define bt3GetMonitorCount GetMonitorCount
#define bt3GetMonitorHeight GetMonitorHeight
#define bt3GetMonitorWidth GetMonitorWidth
#define bt3GetMousePosition GetMousePosition
#define bt3GetMouseWheelMoveV GetMouseWheelMoveV
#define bt3GetPixelDataSize GetPixelDataSize
#define bt3GetRenderHeight GetRenderHeight
#define bt3GetRenderWidth GetRenderWidth
#define bt3GetScreenHeight GetScreenHeight
#define bt3GetScreenWidth GetScreenWidth
#define bt3GetShaderLocation GetShaderLocation
#define bt3GetTime GetTime
#define bt3ImageCopy ImageCopy
#define bt3ImageFlipVertical ImageFlipVertical
#define bt3ImageFormat ImageFormat
#define bt3ImageResize ImageResize
#define bt3InitWindow InitWindow
#define bt3IsGamepadAvailable IsGamepadAvailable
#define bt3IsGamepadButtonPressed IsGamepadButtonPressed
#define bt3IsKeyDown IsKeyDown
#define bt3IsKeyPressed IsKeyPressed
#define bt3IsMouseButtonDown IsMouseButtonDown
#define bt3IsWindowFullscreen IsWindowFullscreen
#define bt3IsWindowReady IsWindowReady
#define bt3IsWindowResized IsWindowResized
#define bt3LoadImage LoadImage
#define bt3LoadImageFromMemory LoadImageFromMemory
#define bt3LoadImageFromScreen LoadImageFromScreen
#define bt3LoadImageFromTexture LoadImageFromTexture
#define bt3LoadShaderFromMemory LoadShaderFromMemory
#define bt3LoadTextureFromImage LoadTextureFromImage
#define bt3PollInputEvents PollInputEvents
#define bt3rlActiveDrawBuffers rlActiveDrawBuffers
#define bt3rlActiveTextureSlot rlActiveTextureSlot
#define bt3rlBegin rlBegin
#define bt3rlCheckRenderBatchLimit rlCheckRenderBatchLimit
#define bt3rlClearColor rlClearColor
#define bt3rlClearScreenBuffers rlClearScreenBuffers
#define bt3rlColor4ub rlColor4ub
#define bt3rlColorMask rlColorMask
#define bt3rlDisableBackfaceCulling rlDisableBackfaceCulling
#define bt3rlDisableColorBlend rlDisableColorBlend
#define bt3rlDisableDepthMask rlDisableDepthMask
#define bt3rlDisableDepthTest rlDisableDepthTest
#define bt3rlDisableFramebuffer rlDisableFramebuffer
#define bt3rlDisableScissorTest rlDisableScissorTest
#define bt3rlDisableShader rlDisableShader
#define bt3rlDisableTexture rlDisableTexture
#define bt3rlDrawRenderBatchActive rlDrawRenderBatchActive
#define bt3rlEnableColorBlend rlEnableColorBlend
#define bt3rlEnableDepthMask rlEnableDepthMask
#define bt3rlEnableDepthTest rlEnableDepthTest
#define bt3rlEnableFramebuffer rlEnableFramebuffer
#define bt3rlEnableScissorTest rlEnableScissorTest
#define bt3rlEnd rlEnd
#define bt3rlFramebufferAttach rlFramebufferAttach
#define bt3rlFramebufferComplete rlFramebufferComplete
#define bt3rlLoadIdentity rlLoadIdentity
#define bt3rlMatrixMode rlMatrixMode
#define bt3rlNormal3f rlNormal3f
#define bt3rlOrtho rlOrtho
#define bt3rlScalef rlScalef
#define bt3rlScissor rlScissor
#define bt3rlSetBlendFactors rlSetBlendFactors
#define bt3rlSetBlendFactorsSeparate rlSetBlendFactorsSeparate
#define bt3rlSetBlendMode rlSetBlendMode
#define bt3rlSetFramebufferHeight rlSetFramebufferHeight
#define bt3rlSetFramebufferWidth rlSetFramebufferWidth
#define bt3rlSetShader rlSetShader
#define bt3rlSetTexture rlSetTexture
#define bt3rlTexCoord2f rlTexCoord2f
#define bt3rlTextureParameters rlTextureParameters
#define bt3rlTranslatef rlTranslatef
#define bt3rlVertex2f rlVertex2f
#define bt3rlVertex3f rlVertex3f
#define bt3rlViewport rlViewport
#define bt3SetClipboardText SetClipboardText
#define bt3SetConfigFlags SetConfigFlags
#define bt3SetShaderValue SetShaderValue
#define bt3SetShaderValueTexture SetShaderValueTexture
#define bt3SetTargetFPS SetTargetFPS
#define bt3SetTextureFilter SetTextureFilter
#define bt3SetTextureWrap SetTextureWrap
#define bt3SetWindowIcon SetWindowIcon
#define bt3SetWindowMonitor SetWindowMonitor
#define bt3SetWindowSize SetWindowSize
#define bt3SetWindowState SetWindowState
#define bt3SetWindowTitle SetWindowTitle
#define bt3SwapScreenBuffer SwapScreenBuffer
#define bt3ToggleFullscreen ToggleFullscreen
#define bt3UnloadImage UnloadImage
#define bt3UnloadTexture UnloadTexture
#define bt3UpdateTexture UpdateTexture
#define bt3WaitTime WaitTime
#define bt3WindowShouldClose WindowShouldClose

#define bt3GetWindowHandle GetWindowHandle   // returns void*: the declaration regex missed the extra star

// ---- constants ---------------------------------------------------------------------
#define BT3_BLEND_ALPHA BLEND_ALPHA
#define BT3_BLEND_CUSTOM BLEND_CUSTOM
#define BT3_BLEND_CUSTOM_SEPARATE BLEND_CUSTOM_SEPARATE
#define BT3_KEY_A KEY_A
#define BT3_KEY_B KEY_B
#define BT3_KEY_BACKSPACE KEY_BACKSPACE
#define BT3_KEY_DELETE KEY_DELETE
#define BT3_KEY_DOWN KEY_DOWN
#define BT3_KEY_END KEY_END
#define BT3_KEY_ENTER KEY_ENTER
#define BT3_KEY_ESCAPE KEY_ESCAPE
#define BT3_KEY_F1 KEY_F1
#define BT3_KEY_F10 KEY_F10
#define BT3_KEY_F11 KEY_F11
#define BT3_KEY_F9 KEY_F9
#define BT3_KEY_G KEY_G
#define BT3_KEY_HOME KEY_HOME
#define BT3_KEY_LEFT KEY_LEFT
#define BT3_KEY_LEFT_ALT KEY_LEFT_ALT
#define BT3_KEY_LEFT_CONTROL KEY_LEFT_CONTROL
#define BT3_KEY_LEFT_SHIFT KEY_LEFT_SHIFT
#define BT3_KEY_PAGE_DOWN KEY_PAGE_DOWN
#define BT3_KEY_PAGE_UP KEY_PAGE_UP
#define BT3_KEY_R KEY_R
#define BT3_KEY_RIGHT KEY_RIGHT
#define BT3_KEY_RIGHT_ALT KEY_RIGHT_ALT
#define BT3_KEY_RIGHT_CONTROL KEY_RIGHT_CONTROL
#define BT3_KEY_RIGHT_SHIFT KEY_RIGHT_SHIFT
#define BT3_KEY_SPACE KEY_SPACE
#define BT3_KEY_TAB KEY_TAB
#define BT3_KEY_UP KEY_UP
#define BT3_KEY_W KEY_W
#define BT3_KEY_ZERO KEY_ZERO
#define BT3_MOUSE_BUTTON_LEFT MOUSE_BUTTON_LEFT
#define BT3_MOUSE_BUTTON_MIDDLE MOUSE_BUTTON_MIDDLE
#define BT3_MOUSE_BUTTON_RIGHT MOUSE_BUTTON_RIGHT
#define BT3_PIXELFORMAT_COMPRESSED_DXT1_RGB PIXELFORMAT_COMPRESSED_DXT1_RGB
// Needed by ps2tex::replacementAlphaMinMax, which reads a pack replacement's alpha range straight
// out of its BC3 blocks. raylib's spelling is DXT5_RGBA (no trailing _RGBA on DXT5 itself).
#define BT3_PIXELFORMAT_COMPRESSED_DXT5_RGBA PIXELFORMAT_COMPRESSED_DXT5_RGBA
#define BT3_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 PIXELFORMAT_UNCOMPRESSED_R8G8B8A8
#define BT3RL_ATTACHMENT_COLOR_CHANNEL0 RL_ATTACHMENT_COLOR_CHANNEL0
#define BT3RL_ATTACHMENT_TEXTURE2D RL_ATTACHMENT_TEXTURE2D
#define BT3RL_BLEND_ALPHA RL_BLEND_ALPHA
#define BT3RL_BLEND_CUSTOM_SEPARATE RL_BLEND_CUSTOM_SEPARATE
#define BT3RL_FREE RL_FREE
#define BT3RL_MALLOC RL_MALLOC
#define BT3RL_MODELVIEW RL_MODELVIEW
#define BT3RL_PROJECTION RL_PROJECTION
#define BT3RL_QUADS RL_QUADS
#define BT3RL_TEXTURE_WRAP_CLAMP RL_TEXTURE_WRAP_CLAMP
#define BT3RL_TEXTURE_WRAP_REPEAT RL_TEXTURE_WRAP_REPEAT
#define BT3RL_TEXTURE_WRAP_S RL_TEXTURE_WRAP_S
#define BT3RL_TEXTURE_WRAP_T RL_TEXTURE_WRAP_T
#define BT3RL_TRIANGLES RL_TRIANGLES
#define BT3_SHADER_UNIFORM_FLOAT SHADER_UNIFORM_FLOAT
#define BT3_SHADER_UNIFORM_INT SHADER_UNIFORM_INT
#define BT3_SHADER_UNIFORM_IVEC4 SHADER_UNIFORM_IVEC4
#define BT3_SHADER_UNIFORM_VEC2 SHADER_UNIFORM_VEC2
#define BT3_SHADER_UNIFORM_VEC4 SHADER_UNIFORM_VEC4

// [video] added for the Video-tab status: monitor name/refresh
#define bt3GetMonitorName GetMonitorName
#define bt3GetMonitorRefreshRate GetMonitorRefreshRate
// [display] added for the Display settings popup
#define bt3SetWindowState SetWindowState
#define bt3ClearWindowState ClearWindowState
#define BT3_FLAG_FULLSCREEN_MODE FLAG_FULLSCREEN_MODE
#define BT3_FLAG_BORDERLESS_WINDOWED_MODE FLAG_BORDERLESS_WINDOWED_MODE
#define BT3_FLAG_WINDOW_RESIZABLE FLAG_WINDOW_RESIZABLE
#define BT3_FLAG_WINDOW_UNDECORATED FLAG_WINDOW_UNDECORATED

// [netmenu2d] the custom Dragon Net menu (2D drawing via raylib, no ImGui)
#define bt3DrawText DrawText
#define bt3DrawTextEx DrawTextEx
#define bt3LoadFont LoadFont
#define bt3LoadFontEx LoadFontEx
#define bt3GetFontDefault GetFontDefault
#define bt3MeasureText MeasureText
#define bt3MeasureTextEx MeasureTextEx
#define bt3DrawRectangleRec DrawRectangleRec
#define bt3DrawRectangleGradientV DrawRectangleGradientV
#define bt3DrawRectangleGradientEx DrawRectangleGradientEx
#define bt3DrawRectangleLinesEx DrawRectangleLinesEx
#define bt3DrawRectangleRounded DrawRectangleRounded
#define bt3DrawRectangleRoundedLinesEx DrawRectangleRoundedLinesEx
#define bt3DrawCircleV DrawCircleV
#define bt3DrawLineEx DrawLineEx
#define bt3DrawTexture DrawTexture
#define bt3DrawTextureV DrawTextureV
#define bt3DrawTextureRec DrawTextureRec
#define bt3Fade Fade
#define bt3BeginScissorMode BeginScissorMode
#define bt3EndScissorMode EndScissorMode
#define BT3_TEXTURE_FILTER_POINT TEXTURE_FILTER_POINT
#define BT3_TEXTURE_FILTER_BILINEAR TEXTURE_FILTER_BILINEAR
